// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var TrackList$ReactHooksTemplate = require("./TrackList.bs.js");
var MusicPlayer$ReactHooksTemplate = require("./MusicPlayer.bs.js");
var PlayerControls$ReactHooksTemplate = require("./PlayerControls.bs.js");

function App(Props) {
  return React.createElement("div", {
              className: "section is-fullheignt"
            }, React.createElement("div", {
                  className: "container"
                }, React.createElement("h1", {
                      className: "is-size-2 has-text-centered is-capitalized"
                    }, "Reason Music Player"), React.createElement("br", undefined), React.createElement("div", {
                      className: "column is-4 is-offset-4"
                    }, React.createElement(MusicPlayer$ReactHooksTemplate.make, {
                          children: null
                        }, React.createElement(TrackList$ReactHooksTemplate.make, { }), React.createElement(PlayerControls$ReactHooksTemplate.make, { })))));
}

var make = App;

exports.make = make;
/* react Not a pure module */
