// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Hello World"));
}

var make = App;

exports.make = make;
/* react Not a pure module */
