// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var initialState_001 = /* tracks : array */[
  /* record */[
    /* name */"Lost Chameleon - Genesis",
    /* file */"LostChameleon"
  ],
  /* record */[
    /* name */"The Hipsta - Shaken Soda",
    /* file */"Rock"
  ],
  /* record */[
    /* name */"Tobu - Such Fun",
    /* file */"Tobu"
  ]
];

var initialState = /* record */[
  /* audioPlayer */"audio",
  initialState_001,
  /* currentTrackIndex */undefined,
  /* isPlaying */false
];

function reducer(state, action) {
  return state;
}

var musicPlayerContext = React.createContext(/* tuple */[
      initialState,
      (function (prim) {
          return /* () */0;
        })
    ]);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = musicPlayerContext.Provider;

var MusicPlayerProvider = /* module */[
  /* makeProps */makeProps,
  /* make */make
];

function MusicPlayer(Props) {
  var children = Props.children;
  var match = React.useReducer(reducer, initialState);
  return React.createElement(make, makeProps(/* tuple */[
                  match[0],
                  match[1]
                ], children, /* () */0));
}

var make$1 = MusicPlayer;

exports.initialState = initialState;
exports.reducer = reducer;
exports.musicPlayerContext = musicPlayerContext;
exports.MusicPlayerProvider = MusicPlayerProvider;
exports.make = make$1;
/* musicPlayerContext Not a pure module */
