// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var initialState_001 = /* tracks : array */[
  /* record */[
    /* name */"Lost Chameleon - Genesis",
    /* file */"LostChameleon"
  ],
  /* record */[
    /* name */"The Hipsta - Shaken Soda",
    /* file */"Rock"
  ],
  /* record */[
    /* name */"Tobu - Such Fun",
    /* file */"Tobu"
  ]
];

var initialState = /* record */[
  /* audioPlayer */"audio",
  initialState_001,
  /* currentTrackIndex */undefined,
  /* isPlaying */false
];

var musicPlayerContext = React.createContext(initialState);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = musicPlayerContext.Provider;

var MusicPlayerProvider = /* module */[
  /* makeProps */makeProps,
  /* make */make
];

exports.initialState = initialState;
exports.musicPlayerContext = musicPlayerContext;
exports.MusicPlayerProvider = MusicPlayerProvider;
/* musicPlayerContext Not a pure module */
