// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as BensoundSummerMp3 from "./bensound-summer.mp3";
import * as BensoundUkuleleMp3 from "./bensound-ukulele.mp3";
import * as BensoundCreativemindsMp3 from "./bensound-creativeminds.mp3";

var summer = BensoundSummerMp3.default;

var ukulele = BensoundUkuleleMp3.default;

var creativeminds = BensoundCreativemindsMp3.default;

var initialState_tracks = [
  {
    name: "Benjamin Tissot - Summer",
    file: summer
  },
  {
    name: "Benjamin Tissot - Ukulele",
    file: ukulele
  },
  {
    name: "Benjamin Tissot - Creative Minds",
    file: creativeminds
  }
];

var initialState_audioPlayer = new Audio("");

var initialState = {
  tracks: initialState_tracks,
  playing: /* NotPlaying */0,
  audioPlayer: initialState_audioPlayer
};

function withPauseTrack(state) {
  return {
          tracks: state.tracks,
          playing: /* NotPlaying */0,
          audioPlayer: state.audioPlayer
        };
}

function withPlayTrack(state, index) {
  return {
          tracks: state.tracks,
          playing: /* Playing */{
            _0: index
          },
          audioPlayer: new Audio(Caml_array.caml_array_get(state.tracks, index).file)
        };
}

function reducer(state, action) {
  if (action) {
    return withPlayTrack(state, action._0);
  } else {
    return withPauseTrack(state);
  }
}

var musicPlayerContext = React.createContext([
      initialState,
      (function (prim) {
          
        })
    ]);

var musicPlayerContextProvider = musicPlayerContext.Provider;

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = musicPlayerContext.Provider;

var MusicPlayerProvider = {
  makeProps: makeProps,
  make: make
};

function MusicPlayer(Props) {
  var children = Props.children;
  var match = React.useReducer(reducer, initialState);
  var state = match[0];
  React.useEffect((function () {
          var _idx = state.playing;
          if (_idx) {
            state.audioPlayer.play();
          } else {
            state.audioPlayer.pause();
          }
          
        }), [state.playing]);
  return React.createElement(make, makeProps([
                  state,
                  match[1]
                ], children, undefined));
}

var make$1 = MusicPlayer;

export {
  summer ,
  ukulele ,
  creativeminds ,
  initialState ,
  withPauseTrack ,
  withPlayTrack ,
  reducer ,
  musicPlayerContext ,
  musicPlayerContextProvider ,
  MusicPlayerProvider ,
  make$1 as make,
  
}
/* summer Not a pure module */
