// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as UseMusicPlayer$ReasonMusicPlayer from "./UseMusicPlayer.bs.js";

function PlayerControls(Props) {
  var match = UseMusicPlayer$ReasonMusicPlayer.useMusicPlayer(/* () */0);
  var togglePlay = match[4];
  var currentTrackIndex = match[2];
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "box controls has-background-grey-dark"
                }, React.createElement("div", {
                      className: "current-track has-text-light"
                    }, React.createElement("marquee", undefined, match[3])), React.createElement("div", {
                      className: "has-text-centered"
                    }, React.createElement("button", {
                          className: "button has-text-light has-background-grey-dark",
                          disabled: currentTrackIndex === undefined,
                          onClick: match[6]
                        }, React.createElement("i", {
                              className: "fas fa-step-backward"
                            })), React.createElement("button", {
                          className: "button has-text-light has-background-grey-dark",
                          disabled: currentTrackIndex === undefined,
                          onClick: (function (param) {
                              return Curry._1(togglePlay, /* () */0);
                            })
                        }, match[0] ? React.createElement("i", {
                                className: "fas fa-pause"
                              }) : React.createElement("i", {
                                className: "fa fa-play"
                              })), React.createElement("button", {
                          className: "button has-text-light has-background-grey-dark",
                          disabled: currentTrackIndex === undefined,
                          onClick: match[7]
                        }, React.createElement("i", {
                              className: "fas fa-step-forward"
                            })))));
}

var make = PlayerControls;

export {
  make ,
  
}
/* react Not a pure module */
