// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var MusicPlayer$ReactHooksTemplate = require("./MusicPlayer.bs.js");

function TrackList(Props) {
  var match = React.useContext(MusicPlayer$ReactHooksTemplate.musicPlayerContext);
  return React.createElement(React.Fragment, undefined, $$Array.map((function (track) {
                    return React.createElement("div", {
                                className: "box"
                              }, React.createElement("div", {
                                    className: "song-title"
                                  }, track[/* name */0]));
                  }), match[0][/* tracks */1]));
}

var make = TrackList;

exports.make = make;
/* react Not a pure module */
