// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var MusicPlayerContext$ReactHooksTemplate = require("./MusicPlayerContext.bs.js");

function reducer(state, action) {
  return state;
}

function TrackList(Props) {
  var initialState = React.useContext(MusicPlayerContext$ReactHooksTemplate.musicPlayerContext);
  var match = React.useReducer(reducer, initialState);
  return React.createElement(React.Fragment, undefined, $$Array.map((function (track) {
                    return React.createElement("div", {
                                className: "box"
                              }, React.createElement("div", {
                                    className: "song-title"
                                  }, track[/* name */0]));
                  }), match[0][/* tracks */1]));
}

var make = TrackList;

exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
