// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";
import * as MusicPlayer$ReasonMusicPlayer from "./MusicPlayer.bs.js";

function useMusicPlayer(param) {
  var match = React.useContext(MusicPlayer$ReasonMusicPlayer.musicPlayerContext);
  var dispatch = match[1];
  var state = match[0];
  var playing = state[/* playing */1];
  var trackList = state[/* tracks */0];
  var currentTrackName = playing ? Caml_array.caml_array_get(state[/* tracks */0], playing[0])[/* name */0] : "Please choose a track to play";
  var togglePlay = function (param) {
    return Curry._1(dispatch, /* TogglePlay */0);
  };
  var playTrack = function (index) {
    if (playing) {
      var match = index === playing[0];
      if (match) {
        return Curry._1(dispatch, /* TogglePlay */0);
      } else {
        state[/* audioPlayer */2].pause();
        return Curry._1(dispatch, /* PlayTrack */[index]);
      }
    } else {
      return Curry._1(dispatch, /* PlayTrack */[index]);
    }
  };
  var trackListLength = trackList.length;
  var playPreviousTrack = function (param) {
    if (playing) {
      return playTrack(Caml_int32.mod_(Caml_int32.mod_(playing[0] - 1 | 0, trackListLength) + trackListLength | 0, trackListLength));
    } else {
      return /* () */0;
    }
  };
  var playNextTrack = function (param) {
    if (playing) {
      return playTrack(Caml_int32.mod_(playing[0] + 1 | 0, trackListLength));
    } else {
      return /* () */0;
    }
  };
  return /* tuple */[
          playing,
          trackList,
          currentTrackName,
          togglePlay,
          playTrack,
          playPreviousTrack,
          playNextTrack
        ];
}

export {
  useMusicPlayer ,
  
}
/* react Not a pure module */
