name: Build Reason

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
        matrix:
          node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: pnpm/action-setup@v1.2.0
      with:
        version: 5.4.12
        run_install: true

    - run: pnpm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        publish_dir: ./build
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}
